skip rpm-query-in-scriptlet.spec on FreeBSD
because of:
+ cd /
+ cpio -pumdL /usr/home/cpansand/.cpan/build/2020042509/urpmi-v8.121.15-2/t/tmp/BUILDROOT/rpm-query-in-scriptlet-1-1.x86_64
cpio: Can't stat /bin/sh:
cpio: Can't stat /usr/local/bin/rpm:
24035 blocks
error: Bad exit status from /usr/home/cpansand/.cpan/build/2020042509/urpmi-v8.121.15-2/t/tmp/rpm-tmp.Q4A94o (%install)

See related debuging in:
http://www.cpantesters.org/cpan/report/e7284484-878b-11ea-a99d-f0811f24ea8f

+ grep / list
+ ls -l /usr/local/lib/libnss3.so /bin/sh /bin/sh: /lib/libedit.so.7 /lib/libc.so.7 /lib/libncursesw.so.9 /usr/local/bin/rpm /usr/local/bin/rpm: /usr/local/lib/librpm.so.9 /usr/local/lib/librpmio.so.9 /usr/local/lib/libdb-5.3.so.0 /usr/local/lib/libnss3.so /usr/lib/libbz2.so.4 /lib/libz.so.6 /usr/local/lib/libpopt.so.0 /usr/lib/liblzma.so.5 /usr/local/lib/libzstd.so.1 /usr/local/lib/liblua-5.2.so /lib/libm.so.5 /lib/libthr.so.3 /usr/local/lib/libintl.so.8 /lib/libc.so.7 /usr/local/lib/libnssutil3.so /usr/local/lib/libplc4.so /usr/local/lib/libplds4.so /usr/local/lib/libnspr4.so /usr/lib/libdl.so.1
ls: /bin/sh:: No such file or directory
ls: /usr/local/bin/rpm:: No such file or directory
error: Bad exit status from /usr/home/cpansand/.cpan/build/2020042520/urpmi-v8.121.17-2/t/tmp/rpm-tmp.GcQOIE (%install)