BSD: prevent failing due to broken deps generator
some FreeBSD CPAN smokers sometimes fails with:
error: Couldn't exec /usr/local/lib/rpm/elfdeps: No such file or directory

The testsuite passes smoothly before & after that change.
The only impact is that with that,
t/media/rpm-query-in-scriptlet/rpm-query-in-scriptlet-1-1.x86_64.rpm
lose one requires on one of its own provides:
removed     REQUIRES librpm.so.9()(64bit)

Which is fine.