cpan-testers: fix failing to build some rpms on FreeBSD
unset %__os_install_post fixes to fix FreeBSD failures (RT#131162)
%__os_install_post cause build failures on FreeBSD due to rpm not being adapted:

such as http://www.cpantesters.org/cpan/report/0a319070-86d8-11ea-a1f7-ec411f24ea8f:
+ /usr/local/lib/rpm/brp-compress /usr/local
+ /usr/local/lib/rpm/brp-strip /usr/bin/strip
+ /usr/local/lib/rpm/brp-strip-static-archive /usr/bin/strip
xargs: illegal option -- d
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements] [-S replsize]]
             [-J replstr] [-L number] [-n number [-x]] [-P maxprocs]
             [-s size] [utility [argument ...]]
error: Bad exit status from /usr/home/cpansand/.cpan/build/2020042509/urpmi-v8.121.15-0/t/tmp/rpm-tmp.P9J8JW (%install)

Stripping also often fails on FreeBSD:
/usr/bin/strip: unable to copy file '...BUILDROOT/arch_to_noarch-1-1.x86_64/usr/lib/test-arch_to_noarch/ldconfig' reason: Permission denied

As a side effect, it also fixes:
Error: Could not execute /usr/local/lib/rpm/elfdeps: file or directory not found