cpan-testers: actually needs perl >= 5.10 for //= operator
thus fixing:

     Tried to use 'urpm::args'.
     Error:  syntax error at /data/home/cpansand/.cpan/build/2020010714/urpmi-v8.120.3-4/blib/lib/urpm/util.pm line 71, near "/."
   (Might be a runaway multi-line // string starting on line 69)