testsuite needs rpmtools
actually it really needs genhdlist2 from rpmtools
The later provides a dummy rpmtools.pm package so that cpan testers can
be happy

We need at least 7.11 as previous versions forced vendor dir which is
usually not defined, thus resulting in:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/'
Do not have write permissions on '/'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Which made urpmi's testsuite to fail on most cpan testers due to
genhdlist2 not being available